[tool.poetry]
name = "online-store"
version = "0.1.0"
description = ""
authors = ["SvAS <sv4s.night@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
